// <auto-generated />
using System;
using ConstructionRegistry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionRegistry.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904140822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConstructionRegistry.Models.Adress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateOfChenge")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ConstructionObject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConstructionOrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionOrganizationSubId")
                        .HasColumnType("int");

                    b.Property<int>("ContractCustomerId")
                        .HasColumnType("int");

                    b.Property<double?>("CostOfObject")
                        .HasColumnType("float");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerOrgRespPersonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfApplication")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Invoice")
                        .HasColumnType("int");

                    b.Property<int?>("KadastrIDID")
                        .HasColumnType("int");

                    b.Property<int?>("ObjectAddressID")
                        .HasColumnType("int");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginDocuments")
                        .HasColumnType("int");

                    b.Property<int>("OriginDocumentsSub")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentInvoice")
                        .HasColumnType("int");

                    b.Property<double?>("SpendingOfObject")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("SubContractCustomeringCoefficients")
                        .HasColumnType("float");

                    b.Property<int?>("TypeOfObjectID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ConstructionOrganizationId");

                    b.HasIndex("ConstructionOrganizationSubId");

                    b.HasIndex("ContractCustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerOrgRespPersonID");

                    b.HasIndex("KadastrIDID");

                    b.HasIndex("ObjectAddressID");

                    b.HasIndex("TypeOfObjectID");

                    b.ToTable("ConstructionObjects");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ContractCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ContractCustomerData")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractCustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KontragentID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KontragentID");

                    b.ToTable("ContractCustomers");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.KadastrID", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("KadastrNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KadastrIDs");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.Kontragent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("KontragentAddressID")
                        .HasColumnType("int");

                    b.Property<string>("KontragentINN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontragentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontragentShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NDSRate")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("KontragentAddressID");

                    b.ToTable("Kontragents");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ResponsiblPerson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PersonDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonFIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonKontragentID")
                        .HasColumnType("int");

                    b.Property<string>("PersonPost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PersonKontragentID");

                    b.ToTable("ResponsiblPersons");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.TypeOfObject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypeOfObjects");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ConstructionObject", b =>
                {
                    b.HasOne("ConstructionRegistry.Models.Kontragent", "ConstructionOrganization")
                        .WithMany()
                        .HasForeignKey("ConstructionOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionRegistry.Models.Kontragent", "ConstructionOrganizationSub")
                        .WithMany()
                        .HasForeignKey("ConstructionOrganizationSubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConstructionRegistry.Models.ContractCustomer", "ContractCustomer")
                        .WithMany("ConstructionObjects")
                        .HasForeignKey("ContractCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionRegistry.Models.Kontragent", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionRegistry.Models.ResponsiblPerson", "CustomerOrgRespPerson")
                        .WithMany("ConstructionObjects")
                        .HasForeignKey("CustomerOrgRespPersonID");

                    b.HasOne("ConstructionRegistry.Models.KadastrID", "KadastrID")
                        .WithMany("ConstructionObjects")
                        .HasForeignKey("KadastrIDID");

                    b.HasOne("ConstructionRegistry.Models.Adress", "ObjectAddress")
                        .WithMany("ConstructionObjects")
                        .HasForeignKey("ObjectAddressID");

                    b.HasOne("ConstructionRegistry.Models.TypeOfObject", "TypeOfObject")
                        .WithMany("ConstructionObjects")
                        .HasForeignKey("TypeOfObjectID");

                    b.Navigation("ConstructionOrganization");

                    b.Navigation("ConstructionOrganizationSub");

                    b.Navigation("ContractCustomer");

                    b.Navigation("Customer");

                    b.Navigation("CustomerOrgRespPerson");

                    b.Navigation("KadastrID");

                    b.Navigation("ObjectAddress");

                    b.Navigation("TypeOfObject");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ContractCustomer", b =>
                {
                    b.HasOne("ConstructionRegistry.Models.Kontragent", "Kontragent")
                        .WithMany("Constructs")
                        .HasForeignKey("KontragentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontragent");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.Kontragent", b =>
                {
                    b.HasOne("ConstructionRegistry.Models.Adress", "KontragentAddress")
                        .WithMany()
                        .HasForeignKey("KontragentAddressID");

                    b.Navigation("KontragentAddress");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ResponsiblPerson", b =>
                {
                    b.HasOne("ConstructionRegistry.Models.Kontragent", "PersonKontragent")
                        .WithMany("ResponsiblPersons")
                        .HasForeignKey("PersonKontragentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonKontragent");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.Adress", b =>
                {
                    b.Navigation("ConstructionObjects");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ContractCustomer", b =>
                {
                    b.Navigation("ConstructionObjects");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.KadastrID", b =>
                {
                    b.Navigation("ConstructionObjects");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.Kontragent", b =>
                {
                    b.Navigation("Constructs");

                    b.Navigation("ResponsiblPersons");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.ResponsiblPerson", b =>
                {
                    b.Navigation("ConstructionObjects");
                });

            modelBuilder.Entity("ConstructionRegistry.Models.TypeOfObject", b =>
                {
                    b.Navigation("ConstructionObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
